pipeline:
  name: jhhtp
  identifier: jhhtp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jhhtpconnector
        build: <+input>
  stages:
    - stage:
        name: run
        identifier: run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: pranjandev/jhttp
                    tags:
                      - ${buildNumber}
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
